//! SquirrelDB Rust Client SDK
//! Generated by sdk-generator v0.1.0
//! DO NOT EDIT MANUALLY

pub mod cache;
mod client;
mod error;
pub mod protocol;
pub mod query;
pub mod storage;

pub use client::{ConnectOptions, SquirrelDB, Subscription};
pub use error::{Error, Result};
pub use protocol::{
    ChangeEvent, ClientMessage, Document, Encoding, HandshakeStatus, MessageType, ProtocolFlags,
    ServerMessage, MAGIC, MAX_MESSAGE_SIZE, PROTOCOL_VERSION,
};
pub use storage::{Bucket, StorageClient, StorageError, StorageObject, StorageOptions};
pub use cache::{CacheClient, CacheError, CacheOptions, RespValue};
pub use query::{
    ChangesOptions, FieldExpr, FilterCondition, QueryBuilder, SortDirection, SortSpec,
    StructuredQuery, and, field, not, or, table,
};
